### Get Tracks From Mock
GET http://localhost:8500/api/v1/tracks?coordinates=nzgd2000

Accept: application/json

### Get All Tracks
GET http://localhost:5130/api/doc/tracks?coordinates=nzgd2000
Accept: application/json


### Get Tracks By Region
GET http://localhost:5130/api/doc/tracks?
    regionCode=NZ-WGN \
   &?coordinates=nzgd2000
Accept: application/json